//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.PrestamoLibroes = new HashSet<PrestamoLibro>();
        }
    
        public int IdLibro { get; set; }
        public string NombreLibro { get; set; }
        public System.DateTime FechaLanzamiento { get; set; }
        public string CantidadPaginas { get; set; }
        public bool Disponible { get; set; }
        public int IdEditorial { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamoLibro> PrestamoLibroes { get; set; }
    }
}
