//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoLibro
    {
        public int IdPrestamoLibro { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public bool FueDvuelto { get; set; }
        public string ObservacionEntrega { get; set; }
        public string ObservacionPrestamo { get; set; }
        public int IdLibro { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
